require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TestersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Tester. As you add validations to Tester, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all testers as @testers" do
      tester = Tester.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:testers)).to eq([tester])
    end
  end

  describe "GET #show" do
    it "assigns the requested tester as @tester" do
      tester = Tester.create! valid_attributes
      get :show, {:id => tester.to_param}, valid_session
      expect(assigns(:tester)).to eq(tester)
    end
  end

  describe "GET #new" do
    it "assigns a new tester as @tester" do
      get :new, {}, valid_session
      expect(assigns(:tester)).to be_a_new(Tester)
    end
  end

  describe "GET #edit" do
    it "assigns the requested tester as @tester" do
      tester = Tester.create! valid_attributes
      get :edit, {:id => tester.to_param}, valid_session
      expect(assigns(:tester)).to eq(tester)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Tester" do
        expect {
          post :create, {:tester => valid_attributes}, valid_session
        }.to change(Tester, :count).by(1)
      end

      it "assigns a newly created tester as @tester" do
        post :create, {:tester => valid_attributes}, valid_session
        expect(assigns(:tester)).to be_a(Tester)
        expect(assigns(:tester)).to be_persisted
      end

      it "redirects to the created tester" do
        post :create, {:tester => valid_attributes}, valid_session
        expect(response).to redirect_to(Tester.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved tester as @tester" do
        post :create, {:tester => invalid_attributes}, valid_session
        expect(assigns(:tester)).to be_a_new(Tester)
      end

      it "re-renders the 'new' template" do
        post :create, {:tester => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tester" do
        tester = Tester.create! valid_attributes
        put :update, {:id => tester.to_param, :tester => new_attributes}, valid_session
        tester.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested tester as @tester" do
        tester = Tester.create! valid_attributes
        put :update, {:id => tester.to_param, :tester => valid_attributes}, valid_session
        expect(assigns(:tester)).to eq(tester)
      end

      it "redirects to the tester" do
        tester = Tester.create! valid_attributes
        put :update, {:id => tester.to_param, :tester => valid_attributes}, valid_session
        expect(response).to redirect_to(tester)
      end
    end

    context "with invalid params" do
      it "assigns the tester as @tester" do
        tester = Tester.create! valid_attributes
        put :update, {:id => tester.to_param, :tester => invalid_attributes}, valid_session
        expect(assigns(:tester)).to eq(tester)
      end

      it "re-renders the 'edit' template" do
        tester = Tester.create! valid_attributes
        put :update, {:id => tester.to_param, :tester => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested tester" do
      tester = Tester.create! valid_attributes
      expect {
        delete :destroy, {:id => tester.to_param}, valid_session
      }.to change(Tester, :count).by(-1)
    end

    it "redirects to the testers list" do
      tester = Tester.create! valid_attributes
      delete :destroy, {:id => tester.to_param}, valid_session
      expect(response).to redirect_to(testers_url)
    end
  end

end
